// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roman-vasich/observability-and-integration-testing/testing/integration (interfaces: OrderRepository)
//
// Generated by this command:
//
//	mockgen -mock_names OrderRepository=OrderRepositoryMock -destination=./mock/mock_repository.go -package=mock . OrderRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	integration "github.com/roman-vasich/observability-and-integration-testing/testing/integration"
	gomock "go.uber.org/mock/gomock"
)

// OrderRepositoryMock is a mock of OrderRepository interface.
type OrderRepositoryMock struct {
	ctrl     *gomock.Controller
	recorder *OrderRepositoryMockMockRecorder
	isgomock struct{}
}

// OrderRepositoryMockMockRecorder is the mock recorder for OrderRepositoryMock.
type OrderRepositoryMockMockRecorder struct {
	mock *OrderRepositoryMock
}

// NewOrderRepositoryMock creates a new mock instance.
func NewOrderRepositoryMock(ctrl *gomock.Controller) *OrderRepositoryMock {
	mock := &OrderRepositoryMock{ctrl: ctrl}
	mock.recorder = &OrderRepositoryMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *OrderRepositoryMock) EXPECT() *OrderRepositoryMockMockRecorder {
	return m.recorder
}

// CreateMut mocks base method.
func (m *OrderRepositoryMock) CreateMut(ctx context.Context, order integration.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMut", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMut indicates an expected call of CreateMut.
func (mr *OrderRepositoryMockMockRecorder) CreateMut(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMut", reflect.TypeOf((*OrderRepositoryMock)(nil).CreateMut), ctx, order)
}

// GetByID mocks base method.
func (m *OrderRepositoryMock) GetByID(ctx context.Context, id string) (integration.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(integration.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *OrderRepositoryMockMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*OrderRepositoryMock)(nil).GetByID), ctx, id)
}

// UpdateMut mocks base method.
func (m *OrderRepositoryMock) UpdateMut(ctx context.Context, id string, patch integration.OrderPatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMut", ctx, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMut indicates an expected call of UpdateMut.
func (mr *OrderRepositoryMockMockRecorder) UpdateMut(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMut", reflect.TypeOf((*OrderRepositoryMock)(nil).UpdateMut), ctx, id, patch)
}
